import { Inter } from 'next/font/google'
import './globals.css'
import './user.css'
import 'react-toastify/dist/ReactToastify.css';
import { AuthProvider } from '@/components/Utils/AuthContext';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Sacredspouse-Matrimonial service',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}> <AuthProvider>
          {children}
        </AuthProvider></body>
      
    </html>
  )
}
